#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jan 24 16:45:52 EST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ae302d5aa3284400815652c101d33dae --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot module_commande_tb_behav xil_defaultlib.module_commande_tb -log elaborate.log"
xelab -wto ae302d5aa3284400815652c101d33dae --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot module_commande_tb_behav xil_defaultlib.module_commande_tb -log elaborate.log

