#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 24 16:45:53 EST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim module_commande_tb_behav -key {Behavioral:sim_1:Functional:module_commande_tb} -tclbatch module_commande_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim module_commande_tb_behav -key {Behavioral:sim_1:Functional:module_commande_tb} -tclbatch module_commande_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

